# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/deepu/Desktop/AI-Remote-Patient-Monitoring/AI-Remote-Patient-Monitoring

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/deepu/Desktop/AI-Remote-Patient-Monitoring/AI-Remote-Patient-Monitoring/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/deepu/Desktop/AI-Remote-Patient-Monitoring/AI-Remote-Patient-Monitoring/build/CMakeFiles /Users/deepu/Desktop/AI-Remote-Patient-Monitoring/AI-Remote-Patient-Monitoring/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/deepu/Desktop/AI-Remote-Patient-Monitoring/AI-Remote-Patient-Monitoring/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RemotePatientMonitoring

# Build rule for target.
RemotePatientMonitoring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RemotePatientMonitoring
.PHONY : RemotePatientMonitoring

# fast build rule for target.
RemotePatientMonitoring/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/build
.PHONY : RemotePatientMonitoring/fast

src/AlertManager.o: src/AlertManager.cpp.o
.PHONY : src/AlertManager.o

# target to build an object file
src/AlertManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/AlertManager.cpp.o
.PHONY : src/AlertManager.cpp.o

src/AlertManager.i: src/AlertManager.cpp.i
.PHONY : src/AlertManager.i

# target to preprocess a source file
src/AlertManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/AlertManager.cpp.i
.PHONY : src/AlertManager.cpp.i

src/AlertManager.s: src/AlertManager.cpp.s
.PHONY : src/AlertManager.s

# target to generate assembly for a file
src/AlertManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/AlertManager.cpp.s
.PHONY : src/AlertManager.cpp.s

src/AnomalyDetector.o: src/AnomalyDetector.cpp.o
.PHONY : src/AnomalyDetector.o

# target to build an object file
src/AnomalyDetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/AnomalyDetector.cpp.o
.PHONY : src/AnomalyDetector.cpp.o

src/AnomalyDetector.i: src/AnomalyDetector.cpp.i
.PHONY : src/AnomalyDetector.i

# target to preprocess a source file
src/AnomalyDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/AnomalyDetector.cpp.i
.PHONY : src/AnomalyDetector.cpp.i

src/AnomalyDetector.s: src/AnomalyDetector.cpp.s
.PHONY : src/AnomalyDetector.s

# target to generate assembly for a file
src/AnomalyDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/AnomalyDetector.cpp.s
.PHONY : src/AnomalyDetector.cpp.s

src/Dashboard.o: src/Dashboard.cpp.o
.PHONY : src/Dashboard.o

# target to build an object file
src/Dashboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/Dashboard.cpp.o
.PHONY : src/Dashboard.cpp.o

src/Dashboard.i: src/Dashboard.cpp.i
.PHONY : src/Dashboard.i

# target to preprocess a source file
src/Dashboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/Dashboard.cpp.i
.PHONY : src/Dashboard.cpp.i

src/Dashboard.s: src/Dashboard.cpp.s
.PHONY : src/Dashboard.s

# target to generate assembly for a file
src/Dashboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/Dashboard.cpp.s
.PHONY : src/Dashboard.cpp.s

src/DataGenerator.o: src/DataGenerator.cpp.o
.PHONY : src/DataGenerator.o

# target to build an object file
src/DataGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/DataGenerator.cpp.o
.PHONY : src/DataGenerator.cpp.o

src/DataGenerator.i: src/DataGenerator.cpp.i
.PHONY : src/DataGenerator.i

# target to preprocess a source file
src/DataGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/DataGenerator.cpp.i
.PHONY : src/DataGenerator.cpp.i

src/DataGenerator.s: src/DataGenerator.cpp.s
.PHONY : src/DataGenerator.s

# target to generate assembly for a file
src/DataGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/DataGenerator.cpp.s
.PHONY : src/DataGenerator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RemotePatientMonitoring.dir/build.make CMakeFiles/RemotePatientMonitoring.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RemotePatientMonitoring"
	@echo "... src/AlertManager.o"
	@echo "... src/AlertManager.i"
	@echo "... src/AlertManager.s"
	@echo "... src/AnomalyDetector.o"
	@echo "... src/AnomalyDetector.i"
	@echo "... src/AnomalyDetector.s"
	@echo "... src/Dashboard.o"
	@echo "... src/Dashboard.i"
	@echo "... src/Dashboard.s"
	@echo "... src/DataGenerator.o"
	@echo "... src/DataGenerator.i"
	@echo "... src/DataGenerator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

